In [8]:
import calendar
a=calendar.weekday(2019,11,21)

if (a==1):
    print("Sunday")
elif(a==2):
    print("Monday")
elif(a==3):
    print("Tuesday")
elif(a==4):
    print("Wednsday")
elif(a==5):
    print("Thursday")
elif(a==6):
    print("Friday")
elif(a==7):
    print("Saturday")


Tuesday


In [9]:
a = '1 w 2 r 3g'
a.title()

'1 W 2 R 3G'

In [11]:
def solve(s):
    s=s.split()
    list1=[]
    for i in s:
        list1.append(i.capitalize())
    for j in list1:
        print(j, end=' ')
solve('1 w 2 r 3g')

1 W 2 R 3g 

In [16]:
from tkinter import *
tk = Tk()
canvas = Canvas(tk, width=400, height=400)
canvas.pack()
canvas.create_arc(10,10,200,100,extent=180,style=ARC)
tk.mainloop()

In [19]:
import turtle
t = turtle.pen()
t.begin_fill()
t.forward(100)
t.left(30)
t.left(100)
t.left(30)
t.close()

AttributeError: 'dict' object has no attribute 'begin_fill'

In [114]:
a=[1,2,3]
b=[1,2,3]
c =tuple((a[i],b[i]) for i in range(len(a)))
for i in c:
    print(i,end = " ")

(1, 1) (2, 2) (3, 3) 

In [4]:
"""
Many Popular Python toolboxes/libraries
    1.numPy
    2.SciPy
    3.pandas
    4.SciKit-Learn
Viaualization Libraries
    1.matplotliba
    2.Seaborn
    3.Plotly

"""

'\nMany Popular Python toolboxes/libraries\n    1.numPy\n    2.SciPy\n    3.pandas\n    4.SciKit-Learn\nViaualization Libraries\n    1.matplotliba\n    2.Seaborn\n    3.Plotly\n\n'

In [9]:
import numpy as np
data = np.random.randn(2,3)
data*10
data+data

array([[ 0.31854037,  0.6715654 , -1.16453314],
       [-2.2627828 , -3.76831534,  1.4449094 ]])

array([[ 0.22640967, -1.16982248, -0.68158604],
       [-0.9142656 , -1.62340313,  1.13162705]])

In [10]:
arr = np.array([[1.,2.,3.],[4.,5.,6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [12]:
arr*arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [13]:
arr-arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [16]:
arr**0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [17]:
arr2 = np.array([[0.,4.,1.],[7.,2.,12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [18]:
arr2>arr

array([[False,  True, False],
       [ True, False,  True]])

In [19]:
a = np.random.randint(1,20,6)
a

array([12, 14,  5, 18,  7, 18])

In [29]:
b=np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
b[5:8]=12

In [36]:
b

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [42]:
arr_slice=b[5:8]
arr_slice[0]=5

In [43]:
arr_slice

array([ 5, 12, 12])

In [44]:
b

array([ 0,  1,  2,  3,  4,  5, 12, 12,  8,  9])

In [46]:
arr_slice[:]=64

In [47]:
arr_slice

array([64, 64, 64])

In [48]:
arr

array([[64., 64., 64.],
       [64., 64., 64.]])

In [49]:
b

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [50]:
b_a=b.copy()

In [51]:
b

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [52]:
b[5]=5

In [53]:
b

array([ 0,  1,  2,  3,  4,  5, 64, 64,  8,  9])

In [54]:
b_a

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [55]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [61]:
arr2d[:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [72]:
arr2d[2:,2:]

array([[9]])

In [73]:
arr2d[1,:2]

array([4, 5])

In [86]:
arr2d[:2,1:]=0

In [87]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [83]:
c=np.random.randint(1,20,(3,4,4))

In [84]:
c

array([[[ 3,  8,  2,  7],
        [16, 19,  4,  4],
        [ 5, 14, 11,  2],
        [ 1,  7, 18, 19]],

       [[ 7, 10, 18, 14],
        [15,  5,  3,  5],
        [ 6, 11, 12, 14],
        [ 6,  1,  5, 16]],

       [[ 1,  8, 18, 17],
        [17, 11, 14, 16],
        [15,  6,  2, 12],
        [10,  4,  9, 11]]])

In [85]:
c[1:,1:]

array([[[15,  5,  3,  5],
        [ 6, 11, 12, 14],
        [ 6,  1,  5, 16]],

       [[17, 11, 14, 16],
        [15,  6,  2, 12],
        [10,  4,  9, 11]]])

In [88]:
names = np.array(['bob','joe','will','bob','will','joe','joe'])
data = np.random.randn(7,4)

In [89]:
names

array(['bob', 'joe', 'will', 'bob', 'will', 'joe', 'joe'], dtype='<U4')

In [90]:
data

array([[-0.50658751, -0.13678263, -0.81464087, -0.05128469],
       [ 0.23095428, -0.0156192 , -1.34641798,  0.15228218],
       [ 0.097401  ,  0.18103923, -0.80859744, -0.88113452],
       [ 0.55253626,  0.24259065,  1.0221048 ,  0.07182288],
       [-0.34405573,  0.92722222,  0.51218206, -0.10767186],
       [ 0.97291161,  1.93362796, -1.82736451,  0.061622  ],
       [ 0.83711568, -0.07238643, -0.34131108, -0.16002783]])

In [101]:
names == 'bob'

array([ True, False, False,  True, False, False, False])

In [105]:
data[~(names == 'bob')]


array([[ 0.23095428, -0.0156192 , -1.34641798,  0.15228218],
       [ 0.097401  ,  0.18103923, -0.80859744, -0.88113452],
       [-0.34405573,  0.92722222,  0.51218206, -0.10767186],
       [ 0.97291161,  1.93362796, -1.82736451,  0.061622  ],
       [ 0.83711568, -0.07238643, -0.34131108, -0.16002783]])

In [107]:
data[~(names == 'bob'),2:]

array([[-1.34641798,  0.15228218],
       [-0.80859744, -0.88113452],
       [ 0.51218206, -0.10767186],
       [-1.82736451,  0.061622  ],
       [-0.34131108, -0.16002783]])

In [104]:
data[names == 'bob',3]

array([-0.05128469,  0.07182288])

In [116]:
mask = (names=='bob')|(names=='will')
mask

array([ True, False,  True,  True,  True, False, False])

In [117]:
data[mask]

array([[-0.50658751, -0.13678263, -0.81464087, -0.05128469],
       [ 0.097401  ,  0.18103923, -0.80859744, -0.88113452],
       [ 0.55253626,  0.24259065,  1.0221048 ,  0.07182288],
       [-0.34405573,  0.92722222,  0.51218206, -0.10767186]])

In [118]:
data[data<0]=0

In [119]:
data

array([[0.        , 0.        , 0.        , 0.        ],
       [0.23095428, 0.        , 0.        , 0.15228218],
       [0.097401  , 0.18103923, 0.        , 0.        ],
       [0.55253626, 0.24259065, 1.0221048 , 0.07182288],
       [0.        , 0.92722222, 0.51218206, 0.        ],
       [0.97291161, 1.93362796, 0.        , 0.061622  ],
       [0.83711568, 0.        , 0.        , 0.        ]])

In [120]:
data[names!='joe']=7

In [121]:
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.23095428, 0.        , 0.        , 0.15228218],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.97291161, 1.93362796, 0.        , 0.061622  ],
       [0.83711568, 0.        , 0.        , 0.        ]])

In [122]:
arr1=np.empty((8,4))

In [124]:
for i in range(8):
    arr1[i]=i

In [125]:
arr1

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [126]:
arr1[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [127]:
arr1[[-3,-5,-7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [134]:
arr2=np.arange(32).reshape(8,4)

In [135]:
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [137]:
arr2[[2,1,2,1,1,2,2,2,1,0],[1,0,1,0,2,1,1,0,1,1]]

array([9, 4, 9, 4, 6, 9, 9, 8, 5, 1])

In [138]:
arr3 = np.arange(15).reshape((3,5))
arr3

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [140]:
arr3.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [146]:
arr4 = np.arange(16).reshape((2,2,4))

In [147]:
arr4

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [153]:
arr4.transpose((2,0,1))

array([[[ 0,  4],
        [ 8, 12]],

       [[ 1,  5],
        [ 9, 13]],

       [[ 2,  6],
        [10, 14]],

       [[ 3,  7],
        [11, 15]]])

In [154]:
import pandas as pd

In [161]:
a = pd.Series([9,4,6,9],index=['a','b','c','d'])
a.values
a.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [166]:
a['d']=4

In [168]:
a[['a','c','b']]

a    9
c    9
b    4
dtype: int64

In [170]:
a[a>4]

a    9
c    9
dtype: int64

In [171]:
a*2

a    18
b     8
c    18
d     8
dtype: int64

In [172]:
a

a    9
b    4
c    9
d    4
dtype: int64

In [181]:
sdata = {"india":46000,"Nepal":32000,"usa":55000}

In [182]:
b=pd.Series(sdata,index=['india','usa','Nepal'])
b

india    46000
usa      55000
Nepal    32000
dtype: int64

In [183]:
b

india    46000
usa      55000
Nepal    32000
dtype: int64

In [184]:
c=pd.Series(sdata,index=['india','usa','Nepal','pakistan'])
c

india       46000.0
usa         55000.0
Nepal       32000.0
pakistan        NaN
dtype: float64

In [185]:
b+c

Nepal        64000.0
india        92000.0
pakistan         NaN
usa         110000.0
dtype: float64