## Random Forest Model


### diabets


In [2]:
import pandas as pd
diabetes_df = pd.read_csv("diabetes.csv")
diabetes_df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [3]:
diabetes_df.shape

(768, 9)

In [4]:
diabetes_df.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [5]:
X = diabetes_df.drop("Outcome", axis=1)
Y = diabetes_df['Outcome']

In [6]:
X,Y

(     Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
 0              6      148             72             35        0  33.6   
 1              1       85             66             29        0  26.6   
 2              8      183             64              0        0  23.3   
 3              1       89             66             23       94  28.1   
 4              0      137             40             35      168  43.1   
 ..           ...      ...            ...            ...      ...   ...   
 763           10      101             76             48      180  32.9   
 764            2      122             70             27        0  36.8   
 765            5      121             72             23      112  26.2   
 766            1      126             60              0        0  30.1   
 767            1       93             70             31        0  30.4   
 
      DiabetesPedigreeFunction  Age  
 0                       0.627   50  
 1                    

In [7]:
from sklearn.model_selection import train_test_split
# implementing train_test_split
X_train, X_test, Y_train,Y_test = train_test_split(X,Y,test_size=0.33,random_state=3)
Y_train#,Y_testX_train#, X_test#, 

150    0
457    0
67     0
362    0
451    1
      ..
659    1
256    0
643    0
249    0
664    1
Name: Outcome, Length: 514, dtype: int64

In [8]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier()
rfc.fit(X_train,Y_train)
# prediction
rfc_predict = rfc.predict(X_test)

C:\Users\RGUKT-APSSDC\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


In [9]:
rfc_predict

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0], dtype=int64)

In [10]:
# evaluating performance
from sklearn.model_selection import cross_val_score
from sklearn.metrics import classification_report,confusion_matrix

In [11]:
rfc_cv_score = cross_val_score(rfc,X,Y, cv = 10, scoring='roc_auc')
rfc_cv_score

array([0.74703704, 0.77666667, 0.82296296, 0.70222222, 0.83185185,
       0.83925926, 0.84555556, 0.85148148, 0.72769231, 0.86653846])

In [12]:
print("=== Confusion Matrix ===")
print(confusion_matrix(Y_test,rfc_predict))
print('\n')
print("=== Classification Report ===")
print(classification_report(Y_test,rfc_predict))
print('\n')
print("=== All AUC Scores ===")
print(rfc_cv_score)
print('\n')
print("=== Mean AUC Score ===")
print("Mean AUC Score - Random Forest: ",rfc_cv_score.mean())

=== Confusion Matrix ===
[[126  22]
 [ 53  53]]


=== Classification Report ===
              precision    recall  f1-score   support

           0       0.70      0.85      0.77       148
           1       0.71      0.50      0.59       106

    accuracy                           0.70       254
   macro avg       0.71      0.68      0.68       254
weighted avg       0.71      0.70      0.69       254



=== All AUC Scores ===
[0.74703704 0.77666667 0.82296296 0.70222222 0.83185185 0.83925926
 0.84555556 0.85148148 0.72769231 0.86653846]


=== Mean AUC Score ===
Mean AUC Score - Random Forest:  0.8011267806267807


In [13]:
import numpy as np
from sklearn.model_selection import RandomizedSearchCV
# NO of trees in random forest
n_estimators = [int(x) for x in np.linspace(start=200,stop =2000, num = 10)]
# no of features at every split

max_features = ['auto','sqrt']

# max_deapth
max_depth = [int(x) for x in np.linspace(start=100,stop =500, num = 11)]
max_depth.append(None)

#create random grid
random_grid = {'n_estimators':n_estimators,'max_features':max_features,'max_depth':max_depth}
# random search of parameters

rfc_random = RandomizedSearchCV(estimator=rfc,param_distributions=random_grid,n_iter=100,cv=3,verbose=2,random_state=42,n_jobs=-1)
# fit the model
rfc_random.fit(X_train,Y_train)
#print results
print(rfc_random.best_params_)


Fitting 3 folds for each of 100 candidates, totalling 300 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  33 tasks      | elapsed:   18.8s
[Parallel(n_jobs=-1)]: Done 154 tasks      | elapsed:  1.5min
[Parallel(n_jobs=-1)]: Done 300 out of 300 | elapsed:  3.0min finished


{'n_estimators': 1200, 'max_features': 'sqrt', 'max_depth': 100}


In [14]:

rfc = RandomForestClassifier(n_estimators = 200, max_depth = 140, max_features = 'sqrt')
rfc.fit(X_train, Y_train)
rfc_predict = rfc.predict(X_test)
rfc_cv_score = cross_val_score(rfc, X, Y, cv = 10, scoring = 'roc_auc')
print('=====Confusion Matrix=====')
print(confusion_matrix(Y_test, rfc_predict))
print('\n')
print('====Classification Report=====')
print(classification_report(Y_test, rfc_predict))
print('\n')
print('====All AUC Scores====')
print(rfc_cv_score)
print('\n')
print('====Mean AUC Score====')
print('Mean AUC Score - Random Forest', rfc_cv_score.mean())

=====Confusion Matrix=====
[[127  21]
 [ 41  65]]


====Classification Report=====
              precision    recall  f1-score   support

           0       0.76      0.86      0.80       148
           1       0.76      0.61      0.68       106

    accuracy                           0.76       254
   macro avg       0.76      0.74      0.74       254
weighted avg       0.76      0.76      0.75       254



====All AUC Scores====
[0.78555556 0.83444444 0.8237037  0.73259259 0.80481481 0.84814815
 0.86148148 0.90777778 0.80346154 0.85730769]


====Mean AUC Score====
Mean AUC Score - Random Forest 0.8259287749287749


In [16]:

from sklearn.datasets import make_moons
# make_moons() function is for binary classification
#and will generate a swirl pattern,or two moons.

In [17]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import VotingClassifier

In [18]:
log_clf = LogisticRegression()
rnd_clf = RandomForestClassifier()

In [19]:
X,Y = make_moons(n_samples=100, noise=0.15, random_state=0)

In [20]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=1)

In [22]:
voting_clf = VotingClassifier(estimators = [('lr',log_clf),('rf',rnd_clf)],voting = 'hard')
voting_clf.fit(X_train,Y_train)

C:\Users\RGUKT-APSSDC\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\RGUKT-APSSDC\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


VotingClassifier(estimators=[('lr',
                              LogisticRegression(C=1.0, class_weight=None,
                                                 dual=False, fit_intercept=True,
                                                 intercept_scaling=1,
                                                 l1_ratio=None, max_iter=100,
                                                 multi_class='warn',
                                                 n_jobs=None, penalty='l2',
                                                 random_state=None,
                                                 solver='warn', tol=0.0001,
                                                 verbose=0, warm_start=False)),
                             ('rf',
                              RandomForestClassifier(bootstrap=True,
                                                     class_weight=None,
                                                     criterion='gini',
                                           

In [23]:
from sklearn.metrics import accuracy_score
for clf in (log_clf,rnd_clf,voting_clf):
    clf.fit(X_train,Y_train)
    y_pred = clf.predict(X_test)
    print(clf.__class__.__name__,accuracy_score(Y_test,y_pred))

LogisticRegression 0.85
RandomForestClassifier 0.9
VotingClassifier 0.95


C:\Users\RGUKT-APSSDC\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\RGUKT-APSSDC\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\RGUKT-APSSDC\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [29]:
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
bag_clf = BaggingClassifier(DecisionTreeClassifier(),n_estimators=500,max_samples=10,bootstrap=True,n_jobs=-1)
bag_clf

BaggingClassifier(base_estimator=DecisionTreeClassifier(class_weight=None,
                                                        criterion='gini',
                                                        max_depth=None,
                                                        max_features=None,
                                                        max_leaf_nodes=None,
                                                        min_impurity_decrease=0.0,
                                                        min_impurity_split=None,
                                                        min_samples_leaf=1,
                                                        min_samples_split=2,
                                                        min_weight_fraction_leaf=0.0,
                                                        presort=False,
                                                        random_state=None,
                                                        splitter='best'),
    

In [30]:
bag_clf.fit(X_train,Y_train)
y_pred = bag_clf.predict(X_test)

In [31]:
accuracy_score(Y_test,y_pred)

0.9