## nav

In [9]:
import pandas as pd
from sklearn.datasets import load_wine
wine = load_wine()
wine

{'data': array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
         1.065e+03],
        [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
         1.050e+03],
        [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
         1.185e+03],
        ...,
        [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
         8.350e+02],
        [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
         8.400e+02],
        [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
         5.600e+02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1

In [18]:
X = 

'.. _wine_dataset:\n\nWine recognition dataset\n------------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 178 (50 in each of three classes)\n    :Number of Attributes: 13 numeric, predictive attributes and the class\n    :Attribute Information:\n \t\t- Alcohol\n \t\t- Malic acid\n \t\t- Ash\n\t\t- Alcalinity of ash  \n \t\t- Magnesium\n\t\t- Total phenols\n \t\t- Flavanoids\n \t\t- Nonflavanoid phenols\n \t\t- Proanthocyanins\n\t\t- Color intensity\n \t\t- Hue\n \t\t- OD280/OD315 of diluted wines\n \t\t- Proline\n\n    - class:\n            - class_0\n            - class_1\n            - class_2\n\t\t\n    :Summary Statistics:\n    \n    ============================= ==== ===== ======= =====\n                                   Min   Max   Mean     SD\n    ============================= ==== ===== ======= =====\n    Alcohol:                      11.0  14.8    13.0   0.8\n    Malic Acid:                   0.74  5.80    2.34  1.12\n    Ash:                     

In [23]:
X = wine.data
Y = wine.target
Y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

In [33]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.3,random_state=1)
X_train,Y_train,X_test,X_train

(array([[1.208e+01, 1.830e+00, 2.320e+00, ..., 1.080e+00, 2.270e+00,
         4.800e+02],
        [1.247e+01, 1.520e+00, 2.200e+00, ..., 1.160e+00, 2.630e+00,
         9.370e+02],
        [1.387e+01, 1.900e+00, 2.800e+00, ..., 1.250e+00, 3.400e+00,
         9.150e+02],
        ...,
        [1.349e+01, 1.660e+00, 2.240e+00, ..., 9.800e-01, 2.780e+00,
         4.720e+02],
        [1.293e+01, 2.810e+00, 2.700e+00, ..., 7.700e-01, 2.310e+00,
         6.000e+02],
        [1.305e+01, 1.650e+00, 2.550e+00, ..., 1.120e+00, 2.510e+00,
         1.105e+03]]),
 array([1, 1, 0, 1, 2, 1, 1, 0, 2, 1, 2, 0, 1, 0, 1, 0, 2, 2, 2, 2, 1, 1,
        0, 2, 0, 1, 2, 0, 1, 0, 2, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 2, 1, 1,
        1, 1, 0, 0, 0, 2, 0, 1, 2, 2, 0, 1, 0, 1, 1, 0, 2, 1, 1, 2, 2, 1,
        1, 1, 2, 2, 1, 0, 1, 0, 2, 1, 1, 0, 0, 1, 0, 0, 0, 2, 0, 2, 2, 0,
        1, 1, 2, 0, 1, 1, 0, 0, 0, 1, 1, 0, 2, 2, 1, 1, 1, 0, 2, 2, 2, 2,
        2, 1, 0, 0, 2, 1, 1, 2, 1, 2, 2, 1, 2, 0]),
 array([[1.369e+01, 3.2

In [34]:
from sklearn.naive_bayes import GaussianNB

gnb = GaussianNB()

gnb.fit(X_train,Y_train)
y_pred = gnb.predict(X_test)
y_pred

array([2, 1, 0, 1, 0, 2, 1, 0, 2, 1, 0, 0, 1, 0, 1, 1, 2, 0, 1, 0, 0, 1,
       2, 0, 0, 2, 0, 0, 0, 2, 1, 2, 2, 0, 1, 1, 1, 1, 1, 0, 0, 1, 2, 0,
       0, 0, 1, 0, 0, 0, 1, 2, 2, 0])

In [37]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
ac = accuracy_score(Y_test,y_pred)
cm = confusion_matrix(Y_test,y_pred)
print("Accuracy:",ac)
print("Cm:",cm)

Accuracy: 0.9814814814814815
Cm: [[23  0  0]
 [ 1 18  0]
 [ 0  0 12]]


In [36]:

cm

array([[23,  0,  0],
       [ 1, 18,  0],
       [ 0,  0, 12]], dtype=int64)

In [45]:
wine_df = pd.DataFrame(wine.data,columns=wine.feature_names)
wine_df.head()

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   od280/od315_of_diluted_wines  proline  
0                          3.92   1065.0  
1                          3.40   1050.0  
2                          3.17   1185.0  
3                          3.45   1480.0  
4                          2.93    735.0

In [39]:
data = pd.read_csv("shirts.csv")
data

Height(cms)  Weight(inKgs) T-shirt
0           158             58       M
1           158             59       M
2           158             63       M
3           160             59       M
4           160             60       M
5           163             60       M
6           163             61       M
7           160             64       L
8           163             64       L
9           165             61       L
10          165             62       L
11          165             65       L
12          168             62       L
13          168             63       L
14          168             66       L
15          170             63       L
16          170             64       L
17          170             68       L

In [40]:
height = data["Height(cms)"].values
weight = data['Weight(inKgs)'].values
height,weight

(array([158, 158, 158, 160, 160, 163, 163, 160, 163, 165, 165, 165, 168,
        168, 168, 170, 170, 170], dtype=int64),
 array([58, 59, 63, 59, 60, 60, 61, 64, 64, 61, 62, 65, 62, 63, 66, 63, 64,
        68], dtype=int64))

In [43]:
import numpy as np
distance = []
x1 = 161
y1 = 61
for i in range(len(height)):
    distance.append(np.sqrt((x1 - height[i])**2 + (y1 - weight[i])**2))
print(distance)


[4.242640687119285, 3.605551275463989, 3.605551275463989, 2.23606797749979, 1.4142135623730951, 2.23606797749979, 2.0, 3.1622776601683795, 3.605551275463989, 4.0, 4.123105625617661, 5.656854249492381, 7.0710678118654755, 7.280109889280518, 8.602325267042627, 9.219544457292887, 9.486832980505138, 11.40175425099138]


In [44]:
data["Distance"]=distance
data

Height(cms)  Weight(inKgs) T-shirt   Distance
0           158             58       M   4.242641
1           158             59       M   3.605551
2           158             63       M   3.605551
3           160             59       M   2.236068
4           160             60       M   1.414214
5           163             60       M   2.236068
6           163             61       M   2.000000
7           160             64       L   3.162278
8           163             64       L   3.605551
9           165             61       L   4.000000
10          165             62       L   4.123106
11          165             65       L   5.656854
12          168             62       L   7.071068
13          168             63       L   7.280110
14          168             66       L   8.602325
15          170             63       L   9.219544
16          170             64       L   9.486833
17          170             68       L  11.401754

In [67]:

from sklearn.preprocessing import LabelEncoder

data_shirts = LabelEncoder()
data_shirts.fit(data["T-shirt"].values)
data_shirts.transform(data["T-shirt"].values)

array([1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [72]:
X = data.iloc[:,0:2]
Y = data.iloc[:,2]


In [73]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.3,random_state = 3)
X_train,X_test,Y_train,Y_test

(    Height(cms)  Weight(inKgs)
 6           163             61
 7           160             64
 12          168             62
 9           165             61
 17          170             68
 16          170             64
 5           163             60
 0           158             58
 15          170             63
 8           163             64
 3           160             59
 10          165             62,     Height(cms)  Weight(inKgs)
 11          165             65
 2           158             63
 1           158             59
 14          168             66
 4           160             60
 13          168             63, 6     M
 7     L
 12    L
 9     L
 17    L
 16    L
 5     M
 0     M
 15    L
 8     L
 3     M
 10    L
 Name: T-shirt, dtype: object, 11    L
 2     M
 1     M
 14    L
 4     M
 13    L
 Name: T-shirt, dtype: object)

In [70]:
y_predict = knn.predict(X_test)
y_predict

array(['L', 'M', 'M', 'L', 'M', 'L'], dtype=object)

In [ ]:
acc = accuracy_score(Y_test,y_predict)
cmm = confusion_matrix(Y_test,y_predict)
print("Accuracy:",acc)
print("CMM:",cmm)

In [76]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train,Y_train)
y_pred = knn.predict(X_test)
from sklearn import metrics
acc = accuracy_score(Y_test,y_pred)
cmm = confusion_matrix(Y_test,y_pred)
print("Accuracy:",acc)
print("CMM:",cmm)

Accuracy: 1.0
CMM: [[3 0]
 [0 3]]


Accuracy: 1.0
CMM: [[3 0]
 [0 3]]
